### PR TITLE
Added private companies chart

### PR DESCRIPTION
**Pull request by LukeParker**
None of the private companies (go figure) would give hard numbers but they all talked about percentages of their personal treasury. At least this gives some idea of their investment.

### CODE REVIEW

**Comment by Hey** [comment]
I'm not entirely sure considering this is kinda meant for companies that have it on their public balance sheet.
Only transparent companies are welcome I believe.

**Comment by nvk** [comment]
Put this on a second page `/private-companies.html` to start tracking them, we can link from home later once we have some criteria

**Comment by nvk** [comment]
@LukeParker check this out https://github.com/nvk/bitcointreasuries.org/blob/main/private-companies.html

**Comment by LukeParker** [comment]
ACK... Love the change.

**Pull request closed without merging**
